Real_EstateDapper/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;
using Real_EstateDapper.Services.PropertyService;
using X.PagedList.Extensions;

namespace Real_EstateDapper.Controllers
{
    public class DefaultController : Controller
    {
        private readonly IPropertyService _propertyService;

        public DefaultController(IPropertyService propertyService)
        {
            _propertyService = propertyService;
        }

        public async Task<IActionResult> Index(int? page)
        {
            var values = await _propertyService.GetAllPropertyAsync();
            int pageNumber = page ?? 1;
            var pagedList = values.ToPagedList(pageNumber, 6);
            return View(pagedList);
        }
    }
}

Real_EstateDapper/Controllers/PropertyController.cs
using Microsoft.AspNetCore.Mvc;
using Real_EstateDapper.Models;
using Real_EstateDapper.Services.CategoryService;
using Real_EstateDapper.Services.PropertyService;
using X.PagedList.Extensions;

namespace Real_EstateDapper.Controllers
{
    public class PropertyController : Controller
    {
        private readonly IPropertyService _propertyService;
        private readonly ICategoryService _categoryService;

        public PropertyController(IPropertyService propertyService, ICategoryService categoryService)
        {
            _propertyService = propertyService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> LayoutPropertyList(int? page, string offerType, string city, int? categoryId)
        {
            // Kategoriler ve adresler için verileri al
            var categories = await _categoryService.GetAllCategoryAsync();
            var addresses = await _propertyService.GetAllPropertyAddressAsync();

            ViewBag.Categories = categories;
            ViewBag.Addresses = addresses;

            // Tüm mülkleri al
            var allProperties = await _propertyService.GetFilteredProperties(categoryId, offerType, city);

			//// Filtreleme işlemleri
			//if (!string.IsNullOrEmpty(offerType))
			//{
			//    allProperties = allProperties.Where(p => p.OfferType == offerType).ToList();
			//}
			//if (!string.IsNullOrEmpty(city))
			//{
			//    allProperties = allProperties.Where(p => p.Adreess == city).ToList();
			//}
			//if (categoryId.HasValue)
			//{
			//    allProperties = allProperties.Where(p => p.CategoryId == categoryId.Value).ToList();
			//}
			var filterModel = new PropertyFilterModel
			{
				CategoryId = categoryId,
				OfferType = offerType,
				City = city
			};
            ViewBag.model= filterModel;

			// Sayfalama işlemi

			int pageNumber = page ?? 1;
            var pagedList = allProperties.ToPagedList(pageNumber, 9);

            return View(pagedList);
        }



        public async Task<IActionResult> PropertyDetail(int id)
        {
            var values =await _propertyService.GetByIdPropertyAsync(id);
            return View(values);
        }
    }
}

Real_EstateDapper/Views/Shared/Components/_LayoutFilterPropertyComponentPartial/Default.cshtml
@model PropertyFilterModel
 <div class="site-section site-section-sm pb-0">
    <div class="container">
        <div class="row">
<form method="get" action="@Url.Action("LayoutPropertyList", "Property")" class="form-search col-md-12" style="margin-top: -100px;">
    <div class="row align-items-end">

        <div class="col-md-3">
            <label for="offer-types">Durum</label>
            <div class="select-wrap">
                <span class="icon icon-arrow_drop_down"></span>
                <select asp-for="OfferType" id="offer-types" class="form-control d-block rounded-0">
                    <option value="">Durumu</option>
                    <option value="Satılık">Satılık</option>
                    <option value="Kiralık" >Kiralık</option>

                </select>
            </div>
        </div>
        <div class="col-md-3">
            <label for="select-city">Şehir</label>
            <div class="select-wrap">
                <span class="icon icon-arrow_drop_down"></span>
                <select asp-for="City" id="select-city" class="form-control d-block rounded-0">
                    <option value="">Şehir</option>
                    @foreach (var address in @ViewBag.Addresses as List<ResultPropertyDto>)
                    {
                        <option value="@address.Adreess">@address.Adreess</option>
                    }
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <label for="category">Ev Tipi</label>
            <div class="select-wrap">
                <span class="icon icon-arrow_drop_down"></span>
                <select asp-for="CategoryId" id="category" class="form-control d-block rounded-0">
                    <option value="">Tür</option>
                    @foreach (var category in @ViewBag.Categories as IEnumerable<ResultCategoryDto>)
                    {
                  
                         <option value="@category.Id">@category.CategoryName</option> 
                    }
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <input type="submit" class="btn btn-success text-white btn-block rounded-0" value="Search">
        </div>
    </div>
</form>
        </div>
    </div>